# Generated by Django 2.1.1 on 2021-08-06 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'v_classification',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('desc', models.CharField(blank=True, max_length=256, null=True)),
                ('file', models.FileField(upload_to='')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover/')),
                ('status', models.CharField(blank=True, choices=[('0', 'Publishing'), ('1', 'Unpublished')], max_length=1, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('classification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Videos.Classification')),
            ],
        ),
    ]
