# Generated by Django 2.1.1 on 2021-08-07 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0002_auto_20210806_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='video',
            name='collected',
        ),
        migrations.RemoveField(
            model_name='video',
            name='liked',
        ),
        migrations.DeleteModel(
            name='Classification',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
