# Generated by Django 3.2.4 on 2021-08-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0006_videocomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='desc',
            field=models.TextField(blank=True, max_length=320, null=True),
        ),
    ]
