# Generated by Django 3.2.4 on 2021-08-08 01:34

import Videos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0007_alter_video_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='video/%y', validators=[Videos.validators.file_size]),
        ),
    ]
