# Generated by Django 3.2.5 on 2021-07-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Null', max_length=10, verbose_name='username')),
                ('age', models.IntegerField(default=-1, verbose_name='age')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='gender')),
                ('last_name', models.CharField(default='Null', max_length=50, verbose_name='Last Name')),
                ('first_name', models.CharField(default='Null', max_length=50, verbose_name='First Name')),
                ('e_mail', models.CharField(default='Null', max_length=100, verbose_name='e-mail')),
                ('password', models.CharField(default='Null', max_length=100, verbose_name='e-mail')),
            ],
        ),
    ]
