# Generated by Django 3.2.5 on 2021-07-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='Null', max_length=128, verbose_name='password'),
        ),
    ]
