# Generated by Django 3.2.4 on 2021-07-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_rename_user_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='username')),
                ('age', models.IntegerField(null=True, verbose_name='age')),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (0, 'Secret')], verbose_name='gender')),
                ('last_name', models.CharField(max_length=128, verbose_name='last Name')),
                ('first_name', models.CharField(max_length=128, verbose_name='first Name')),
                ('usertype', models.IntegerField(choices=[(0, 'Researcher'), (1, 'Common User')], verbose_name='user type')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=256, verbose_name='password')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
            ],
            options={
                'verbose_name': 'users',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
