# Generated by Django 3.2.4 on 2021-07-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20210715_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('S', 'Secret')], max_length=100, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('R', 'Researcher'), ('C', 'Common User')], max_length=100, verbose_name='user type'),
        ),
    ]
