# Generated by Django 2.1.1 on 2021-08-07 00:11

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20210807_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='avatar/2.png', upload_to='avatar/%Y%m%d/'),
        ),
    ]
