# Generated by Django 3.2.5 on 2021-08-06 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Story', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_name', models.CharField(max_length=500)),
                ('interview_link', models.URLField(max_length=2000)),
                ('start_time', models.TimeField(default='12:00:00')),
                ('end_time', models.TimeField(default='12:00:00')),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('more_details', models.TextField(verbose_name='Provide more details.')),
                ('data_added', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_story_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Story.story')),
            ],
            options={
                'ordering': ('-data_added',),
            },
        ),
    ]
