# Generated by Django 3.2.4 on 2021-07-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='title_name',
            new_name='related_story_name',
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_name',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
