# Generated by Django 3.2.4 on 2021-07-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20210727_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='organiger',
            new_name='organizer',
        ),
    ]
