# Generated by Django 3.2.4 on 2021-07-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_rename_organiger_interview_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='more_details',
            field=models.TextField(default=0, verbose_name='Please provide more details about this Interview appointment.'),
            preserve_default=False,
        ),
    ]
