# Generated by Django 3.2.4 on 2021-07-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_interview_more_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='more_details',
            field=models.TextField(verbose_name='Provide more details.'),
        ),
    ]
