# Generated by Django 3.2.5 on 2021-08-06 08:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(auto_created=True, default=0, verbose_name='views number')),
                ('title_name', models.CharField(max_length=100, verbose_name='title')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='publish time')),
                ('category', models.CharField(choices=[('ComputerScience', 'ComputerScience'), ('Physics', 'Physics'), ('ElectricalEngineering', 'ElectricalEngineering')], max_length=100, null=True, verbose_name='category')),
                ('img', models.ImageField(null=True, upload_to='img', verbose_name='front page')),
                ('text', ckeditor.fields.RichTextField()),
                ('video', models.URLField(blank=True, null=True, verbose_name='video')),
                ('paper_link', models.URLField(blank=True, null=True, verbose_name='paper_link')),
                ('background', models.CharField(default='background', max_length=1000, verbose_name='background')),
                ('tags', models.CharField(default=models.CharField(choices=[('ComputerScience', 'ComputerScience'), ('Physics', 'Physics'), ('ElectricalEngineering', 'ElectricalEngineering')], max_length=100, null=True, verbose_name='category'), max_length=100, verbose_name='tags')),
            ],
            options={
                'verbose_name_plural': 'Stories',
            },
        ),
    ]
