# Generated by Django 3.2.4 on 2021-07-18 17:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=100, verbose_name='title')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='publish time')),
                ('category', models.CharField(choices=[('ComputerScience', 'ComputerScience'), ('Physics', 'Physics'), ('ElectricalEngineering', 'ElectricalEngineering')], max_length=100, verbose_name='category')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='views number')),
                ('text', ckeditor.fields.RichTextField()),
                ('video', models.URLField(blank=True, null=True, verbose_name='video')),
                ('paper_link', models.URLField(blank=True, null=True, verbose_name='paper_link')),
            ],
            options={
                'verbose_name_plural': 'Stories',
            },
        ),
    ]
