# Generated by Django 3.2.5 on 2021-08-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Story', '0002_story_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='img',
            field=models.ImageField(default='img/black-hole-02.0.webp', null=True, upload_to='img', verbose_name='front page'),
        ),
    ]
