# Generated by Django 3.2.4 on 2021-07-20 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Story', '0002_story_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='img',
        ),
    ]
