# Generated by Django 3.2.5 on 2021-08-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Story', '0003_alter_story_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.CharField(default='author', max_length=100, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='story',
            name='author_intro',
            field=models.CharField(default='author introduction', max_length=1000, verbose_name='author_intro'),
        ),
    ]
