# Generated by Django 3.2.4 on 2021-07-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Story', '0003_remove_story_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='img',
            field=models.ImageField(default=0, upload_to='img', verbose_name='front page'),
            preserve_default=False,
        ),
    ]
