# Generated by Django 3.2.4 on 2021-07-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Story', '0004_story_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='views',
            field=models.PositiveIntegerField(auto_created=True, default=0, verbose_name='views number'),
        ),
    ]
