# Generated by Django 2.1.1 on 2021-08-06 20:15

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Story', '0005_auto_20210806_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(default='img/default.png', upload_to='img', verbose_name='front page'),
        ),
    ]
