# Generated by Django 2.1.1 on 2021-08-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Story', '0008_auto_20210806_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='img',
            field=models.ImageField(default='img/black-hole-02.0.webp', null=True, upload_to='img', verbose_name='front page'),
        ),
    ]
