# Generated by Django 3.2.4 on 2021-07-20 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_link_data_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='data_added',
        ),
    ]
