# Generated by Django 3.2.4 on 2021-07-20 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_remove_link_data_added'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
