# Generated by Django 3.2.4 on 2021-07-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_alter_comment_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
