# Generated by Django 3.2.4 on 2021-07-26 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0010_alter_comment_created_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
